import Head from 'next/head'
import MainLayout from '../components/layouts/MainLayout'
import Video from '../components/Video'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <MainLayout>
      <Head>
        <title>Home - Alberta Drone Specialists</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="banner">
        <Video prefix="main" />
        <div id="source"></div>
      </div>

      <section>
        <picture>

        </picture>
        <h2></h2>
      </section>
      <section>
        <h2></h2>
      </section>
      <section>
        <h2></h2>
      </section>
      <section>
        <h2></h2>
      </section>
      <section>
        <h2></h2>
      </section>
    </MainLayout>
  )
}
