import Head from 'next/head'
import MainLayout from '../components/layouts/MainLayout'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <MainLayout>
      <Head>
        <title>Home - Alberta Drone Specialists</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Hello World
      Lorem ipsum dolor sit, amet consectetur adipisicing elit. Corrupti voluptas amet eius nostrum ratione, deleniti repellat aspernatur quia, itaque illum accusantium expedita non, quis dolorem. Voluptatibus excepturi iste animi dignissimos repellendus ratione cupiditate recusandae minus doloremque, quod distinctio assumenda minima non velit dolore necessitatibus, delectus doloribus. Doloribus iste ducimus corrupti blanditiis suscipit voluptas dicta, architecto unde, sequi officia explicabo, earum sint. Possimus blanditiis commodi, quae aut delectus cum illum quas consectetur explicabo libero iste repudiandae. Ut, laborum. Voluptatibus ullam maxime sequi? 
    </MainLayout>
  )
}
